CREATE TABLE `vehicles` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `year` smallint NOT NULL,
  `make` varchar(36) NOT NULL,
  `model` varchar(128) NOT NULL,
  `city_mpg_fuel1` smallint NOT NULL,
  `city_mpg_fuel2` smallint DEFAULT NULL,
  `hwy_mpg_fuel1` smallint NOT NULL,
  `hwy_mpg_fuel2` smallint DEFAULT NULL,
  `comb_mpg_fuel1` smallint NOT NULL,
  `comb_mpg_fuel2` smallint DEFAULT NULL,
  `co2_gpm_fuel1` float DEFAULT NULL,
  `co2_gpm_fuel2` float DEFAULT NULL,
  `cylinders` tinyint DEFAULT NULL,
  `displacement` float DEFAULT NULL,
  `drive` varchar(36) DEFAULT NULL,
  `atv_type` varchar(36) DEFAULT NULL,
  `fuel_type1` varchar(36) DEFAULT '',
  `fuel_type2` varchar(36) DEFAULT NULL,
  `transmission` varchar(128) DEFAULT '',
  `vehicle_class` varchar(128) DEFAULT '',
  `kwh_100_miles` float DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB;
